workflows:
  ios-app:
    name: Build iOS App

    environment:
      xcode: latest
      java: 17

    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Build iOS Application
        script: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build

    artifacts:
      - build/**/*.app